name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: update apt
      run: sudo apt upgrade && sudo apt update
    - name: apt install valgrind
      run: sudo apt install valgrind
    - name: build
      run: make build_linux
    - name: run
      run: make valgrind_linux
